### ISSUE TITLE
@media-queries

### ISSUE THREAD

**Issue by iamale** [tayfunerbilen/LESS-to-SCSS#2]
```less
.full-width-section {
  padding: @desktop-gutter;
  @media @device-small {
    padding-top: (@desktop-gutter * 2);
    padding-bottom: (@desktop-gutter * 2);
  }
}
```

Is treated like this:

```scss
.full-width-section {
  padding: $desktop-gutter;
  $media $device-small {
    padding-top: ($desktop-gutter * 2);
    padding-bottom: ($desktop-gutter * 2);
  }
}
```

But `@media` is not actually a variable. Probably you should blacklist it as well.
